services:
  # Переопределяем способ запуска для разработки (сборка из исходников)
  series-tracker-app:
    build:
      context: ./
    profiles: ["dev"]

  # Prometheus для разработки (targets dev)
  prometheus:
    container_name: prometheus-dev
    volumes:
      - ./prometheus/targets/dev.json:/etc/prometheus/targets/targets.json
    environment:
      PROMETHEUS_ENV: dev
    profiles: ["dev"]