name: series-tracker

services:
  # БД для сервиса series-tracker
  series-tracker-db:
    image: postgres:17.5
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    env_file: .env
    environment:
      POSTGRES_DB: series_tracker_dev
      POSTGRES_SCHEMA: series_tracker
      POSTGRES_PASSWORD: ${DB_SU_PWD}
      PG_DBO_USER: series_tracker_dbo
      PG_DBO_PWD: ${DB_DBO_PWD}
      PG_API_USER: series_tracker_api
      PG_API_PWD: ${DB_API_PWD}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGTZ: Asia/Tomsk
      TZ: Asia/Tomsk
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$PG_DBO_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./series_tracker_db/initdb_scripts:/docker-entrypoint-initdb.d
      - ./series_tracker_db/container_data:/var/lib/postgresql/data
      - ./series_tracker_db/container_conf:/etc/postgresql
    ports:
      - 5432:5432

  # Spring Boot приложение (общая конфигурация)
  series-tracker-app:
    mem_limit: 500m
    env_file: .env
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
      SPRING_DATASOURCE_URL: jdbc:postgresql://series-tracker-db:5432/series_tracker_dev?currentSchema=series_tracker
    volumes:
      - ./logs:/app/logs
    ports:
      - 8090:8090
    restart: unless-stopped
    depends_on:
      series-tracker-db:
        condition: service_healthy

  # Prometheus (общая конфигурация)
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data/:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: Asia/Tomsk

  #loki (общая конфигурация)
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki/data:/loki

  # Grafana (общая конфигурация)
  grafana:
    image: grafana/grafana:latest
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/