services:
  # Переопределяем способ запуска для продакшена (готовый образ)
  series-tracker-app:
    image: series-tracker-app:latest
    profiles: ["prod"]

  # Prometheus для продакшена (targets prod)
  prometheus:
    container_name: prometheus-prod
    volumes:
      - ./prometheus/targets/prod.json:/etc/prometheus/targets/targets.json
    environment:
      PROMETHEUS_ENV: prod
    profiles: ["prod"]