spring:
  application:
    name: seriesparser
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
api:
  movielab:
      username: movielabmbtv
      password: QxWgxbv5oN0C
      login:
        url: https://api.lumex.site/login
      short-info:
        url: https://portal.lumex.host/api/short
        token: 6b313ac178d276c7920257ffe5a8e342
      stream-info:
        url: https://api.lumex.site/stream
        client-id: 3dMif4uaUVYO